//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class goodinfo_Revenues
    {
        public string Date { get; set; }
        public string ID { get; set; }
        public decimal rOpen { get; set; }
        public decimal rHigh { get; set; }
        public decimal rClose { get; set; }
        public decimal rLow { get; set; }
        public decimal UpDownPrice { get; set; }
        public decimal UpDownPercentage { get; set; }
        public decimal Revenue { get; set; }
        public decimal MonthGrowthRate { get; set; }
        public decimal YearGrowthRate { get; set; }
        public decimal TotalRevenue { get; set; }
        public decimal TotalYearGrowthRate { get; set; }
        public decimal CoRevenue { get; set; }
        public decimal CoMonthGrowthRate { get; set; }
        public decimal CoYearGrowthRate { get; set; }
        public decimal CoTotalRevenue { get; set; }
        public decimal CoTotalYearGrowthRate { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    }
}
