//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChipForm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chip
    {
        public string ID { get; set; }
        public string Code { get; set; }
        public string InfoDate { get; set; }
        public int Num { get; set; }
        public string StockLevel { get; set; }
        public string People { get; set; }
        public long ChipCount { get; set; }
        public decimal Ratio { get; set; }
        public string TotalPeople { get; set; }
        public long TotalChipCount { get; set; }
        public decimal TotalRatio { get; set; }
    }
}
