//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChipForm.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public string ID { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public string InfoDate { get; set; }
        public decimal ForeignBuy { get; set; }
        public decimal ForeignSell { get; set; }
        public decimal ForeignNet { get; set; }
        public decimal DomesticBuy { get; set; }
        public decimal DomesticSell { get; set; }
        public decimal DomesticNet { get; set; }
        public decimal DealerNet { get; set; }
        public decimal TotalNet { get; set; }
        public string Category { get; set; }
    }
}
